# Use the official MySQL 8.0 image as the base
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=0000
ENV MYSQL_DATABASE=hospital_2

# Expose the MySQL port
EXPOSE 3306

# Copy an optional initialization script (if needed)
COPY init.sql /docker-entrypoint-initdb.d/